#!/bin/bash
exec /sbin/setuser abc java -jar /app/ubooquity/Ubooquity.jar --webadmin --headless --host 0.0.0.0 --port 2202 --workdir /app/ubooquity
sleep 2s
exec /sbin/setuser abc tail -F /app/ubooquity/log/ubooquity.log
